from O_S_model import one2seven_model

Info_data = {
        "scheduledCycle": "5.0",
        "salaries": ["3000.0", "3205.0", "3500.0"],
        "terminal": [{
            "x_axis": "2245000.0",
            "y_axis": "434600.0",
            "workers": ["1.0", "2.0", "3.0", "4.0", "5.0"],
            "oneLevelWorkers": ["12.0", "12.0", "12.0", "12.0", "12.0"],
            "twoLevelWorkers": ["12.0", "12.0", "12.0", "12.0", "12.0"],
            "thirdLevelWorkers": ["12.0", "12.0", "12.0", "12.0", "12.0"]
        }],
        "windFactory": [{
            "furnaces": [
                {
                    "number": "0.0",
                    "x_axis": "2278055.0",
                    "y_axis": "456571.0"
                }, {
                    "number": "1.0",
                    "x_axis": "2278616.0",
                    "y_axis": "456845.0"
                }, {
                    "number": "2.0",
                    "x_axis": "2276290.0",
                    "y_axis": "457345.0"
                }, {
                    "number": "3.0",
                    "x_axis": "2276850.0",
                    "y_axis": "457618.0"
                }, {
                    "number": "4.0",
                    "x_axis": "2277411.0",
                    "y_axis": "457892.0"
                }, {
                    "number": "5.0",
                    "x_axis": "2277972.0",
                    "y_axis": "458165.0"
                }, {
                    "number": "6.0",
                    "x_axis": "2278532.0",
                    "y_axis": "458439.0"
                }, {
                    "number": "7.0",
                    "x_axis": "2279093.0",
                    "y_axis": "458712.0"
                }, {
                    "number": "8.0",
                    "x_axis": "2279654.0",
                    "y_axis": "458986.0"
                }, {
                    "number": "9.0",
                    "x_axis": "2276236.0",
                    "y_axis": "458959.0"
                }, {
                    "number": "10.0",
                    "x_axis": "2276767.0",
                    "y_axis": "459213.0"
                }, {
                    "number": "11.0",
                    "x_axis": "2277327.0",
                    "y_axis": "459486.0"
                }, {
                    "number": "12.0",
                    "x_axis": "2277888.0",
                    "y_axis": "459760.0"
                }, {
                    "number": "13.0",
                    "x_axis": "2278449.0",
                    "y_axis": "460033.0"
                }, {
                    "number": "14.0",
                    "x_axis": "2279009.0",
                    "y_axis": "460307.0"
                }, {
                    "number": "15.0",
                    "x_axis": "2279570.0",
                    "y_axis": "460580.0"
                }, {
                    "number": "16.0",
                    "x_axis": "2280131.0",
                    "y_axis": "460854.0"
                }, {
                    "number": "17.0",
                    "x_axis": "2280691.0",
                    "y_axis": "461127.0"
                }, {
                    "number": "18.0",
                    "x_axis": "2272759.0",
                    "y_axis": "458892.0"
                }, {
                    "number": "19.0",
                    "x_axis": "2273319.0",
                    "y_axis": "459166.0"
                }, {
                    "number": "20.0",
                    "x_axis": "2273880.0",
                    "y_axis": "459440.0"
                }, {
                    "number": "21.0",
                    "x_axis": "2274515.0",
                    "y_axis": "459888.0"
                }, {
                    "number": "22.0",
                    "x_axis": "2275001.0",
                    "y_axis": "459987.0"
                }, {
                    "number": "23.0",
                    "x_axis": "2275562.0",
                    "y_axis": "460260.0"
                }, {
                    "number": "24.0",
                    "x_axis": "2276123.0",
                    "y_axis": "460534.0"
                }, {
                    "number": "25.0",
                    "x_axis": "2276683.0",
                    "y_axis": "460807.0"
                }, {
                    "number": "26.0",
                    "x_axis": "2277244.0",
                    "y_axis": "461081.0"
                }, {
                    "number": "27.0",
                    "x_axis": "2277805.0",
                    "y_axis": "461354.0"
                }, {
                    "number": "28.0",
                    "x_axis": "2270993.0",
                    "y_axis": "459667.0"
                }, {
                    "number": "29.0",
                    "x_axis": "2271554.0",
                    "y_axis": "459989.0"
                }, {
                    "number": "30.0",
                    "x_axis": "2272114.0",
                    "y_axis": "460214.0"
                }, {
                    "number": "31.0",
                    "x_axis": "2272673.0",
                    "y_axis": "460535.0"
                }, {
                    "number": "32.0",
                    "x_axis": "2273236.0",
                    "y_axis": "460761.0"
                }, {
                    "number": "33.0",
                    "x_axis": "2273796.0",
                    "y_axis": "461034.0"
                }, {
                    "number": "34.0",
                    "x_axis": "2274357.0",
                    "y_axis": "461308.0"
                }, {
                    "number": "35.0",
                    "x_axis": "2271129.0",
                    "y_axis": "461261.1"
                }
            ],
            "repairFurnaces": [
                {
                    "number": "1.0",
                    "maintainTime": "4.0",
                    "oneLevelWorker": "2.0",
                    "twoLevelWorker": "0.0",
                    "threeLevelWorker": "1.0",
                    "accessoryWeight": "700.0",
                    "needShip": "0.0",
                    "latestMaintainTime": "3.0",
                    "punishmentCost": "62400.0"
                }, {
                    "number": "7.0",
                    "maintainTime": "3.0",
                    "oneLevelWorker": "0.0",
                    "twoLevelWorker": "1.0",
                    "threeLevelWorker": "1.0",
                    "accessoryWeight": "700.0",
                    "needShip": "0.0",
                    "latestMaintainTime": "2.0",
                    "punishmentCost": "62400.0"
                }, {
                    "number": "9.0",
                    "maintainTime": "5.0",
                    "oneLevelWorker": "3.0",
                    "twoLevelWorker": "0.0",
                    "threeLevelWorker": "0.0",
                    "accessoryWeight": "300.0",
                    "needShip": "1.0",
                    "latestMaintainTime": "4.0",
                    "punishmentCost": "62400.0"
                }, {
                    "number": "12.0",
                    "maintainTime": "2.0",
                    "oneLevelWorker": "1.0",
                    "twoLevelWorker": "0.0",
                    "threeLevelWorker": "2.0",
                    "accessoryWeight": "900.0",
                    "needShip": "0.0",
                    "latestMaintainTime": "1.0",
                    "punishmentCost": "62400.0"
                }, {
                    "number": "16.0",
                    "maintainTime": "4.0",
                    "oneLevelWorker": "1.0",
                    "twoLevelWorker": "2.0",
                    "threeLevelWorker": "2.0",
                    "accessoryWeight": "600.0",
                    "needShip": "0.0",
                    "latestMaintainTime": "1.0",
                    "punishmentCost": "62400.0"
                }, {
                    "number": "17.0",
                    "maintainTime": "5.0",
                    "oneLevelWorker": "3.0",
                    "twoLevelWorker": "0.0",
                    "threeLevelWorker": "0.0",
                    "accessoryWeight": "900.0",
                    "needShip": "1.0",
                    "latestMaintainTime": "1.0",
                    "punishmentCost": "187200.0"
                }, {
                    "number": "20.0",
                    "maintainTime": "2.0",
                    "oneLevelWorker": "2.0",
                    "twoLevelWorker": "2.0",
                    "threeLevelWorker": "1.0",
                    "accessoryWeight": "900.0",
                    "needShip": "0.0",
                    "latestMaintainTime": "4.0",
                    "punishmentCost": "187200.0"
                }, {
                    "number": "23.0",
                    "maintainTime": "2.0",
                    "oneLevelWorker": "3.0",
                    "twoLevelWorker": "0.0",
                    "threeLevelWorker": "1.0",
                    "accessoryWeight": "500.0",
                    "needShip": "0.0",
                    "latestMaintainTime": "1.0",
                    "punishmentCost": "624000.0"
                }
            ]
        }],
        "ships": [
            {
                "capacity": "3900.0",
                "carryPersonal": "12.0",
                "oilFee": "2240.0",
                "spreed": "32.0"
            }, {
                "capacity": "4000.0",
                "carryPersonal": "12.0",
                "oilFee": "2400.0",
                "spreed": "35.0"
            }, {
                "capacity": "4100.0",
                "carryPersonal": "12.0",
                "oilFee": "2160.0",
                "spreed": "30.0"
            }
        ],
        "additionalInfos": [
            {
                "transferTime": "0.25",
                "impi": "1.0",
                "availableTime4Ship1": "6.0",
                "availableTime4Ship2": "6.0",
                "availableTime4Ship3": "6.0"
            }, {
                "transferTime": "0.25",
                "impi": "2.0",
                "availableTime4Ship1": "6.0",
                "availableTime4Ship2": "6.0",
                "availableTime4Ship3": "6.0"
            }, {
                "transferTime": "0.25",
                "impi": "3.0",
                "availableTime4Ship1": "0.0",
                "availableTime4Ship2": "0.0",
                "availableTime4Ship3": "0.0"
            }, {
                "transferTime": "0.25",
                "impi": "4.0",
                "availableTime4Ship1": "10.0",
                "availableTime4Ship2": "12.0",
                "availableTime4Ship3": "10.0"
            }, {
                "transferTime": "0.25",
                "impi": "5.0",
                "availableTime4Ship1": "10.0",
                "availableTime4Ship2": "12.0",
                "availableTime4Ship3": "10.0"
            }
        ]
    };

if __name__ == "__main__":
    one2seven_model(Info_data)